### ISSUE TITLE
Android: Missing OpenAL/SL audio support.

### ISSUE THREAD

**Issue by omcfadde** [omcfadde/dante#20]
I'm tagging this as both a bug and enhancement because it's a pretty serious issue we should try to get fixed as soon as possible. Android is using OpenSL so this is probably what we should aim for on that platform.

**Comment by havlenapetr** [comment]
Done: https://github.com/havlenapetr/adoom3/blob/master/jni/audio.cpp

**Comment by omcfadde** [comment]
Thanks Petr, I'll check the latest code and see about merging it today, before I generate some prebuilt APK packages for those wishing to try the Android build without compiling themselves. I've been quite busy lately, not a lot of free time.

I think we may still have some issues with the audio stuttering due to the low FPS. Optimizations can come later... I think the next step will be to work on profiling and possibly SIMD optimization (which will be using the NEON instruction set on ARM.)

In any case, having somewhat working audio is better than having no audio at all. Thanks for your contribution! :-) I'll leave this issue open for the optimizations, but downgrade it from "bug" status to "enhancement" status once audio is playing.
